name: Compilar APK de Cancionero

on:
  push:
    branches: [ "main", "principal" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el Repositorio
      uses: actions/checkout@v4

    - name: Configurar Java JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Dar Permisos de Ejecución a Gradle
      working-directory: aplicación
      run: chmod +x gradlew
      continue-on-error: true

    - name: Compilar APK (Debug)
      working-directory: aplicación
      run: ./gradlew assembleDebug

    - name: Subir APK Generado
      uses: actions/upload-artifact@v4
      with:
        name: Cancionero-App-Debug
        path: |
          **/build/outputs/apk/debug/*.apk
          **/build/outputs/apk/release/*.apk
